apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
      - name: customer-app
        image: 211125621923.dkr.ecr.us-east-1.amazonaws.com/customer-repo:latest
        ports:
        - containerPort: 8080
